// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalbxWdFzgMFRW2SZu-5edtT1YWQi71Ng',
    appId: '1:267525384609:web:08542c5aa2e0ce0d4d83e0',
    messagingSenderId: '267525384609',
    projectId: 'movie-app-91685',
    authDomain: 'movie-app-91685.firebaseapp.com',
    storageBucket: 'movie-app-91685.firebasestorage.app',
    measurementId: 'G-2M3TPPMJ3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVuvs28A_abNBgjBWY1ts-QHZ5kDD71NA',
    appId: '1:267525384609:android:7ce865be6e67ca194d83e0',
    messagingSenderId: '267525384609',
    projectId: 'movie-app-91685',
    storageBucket: 'movie-app-91685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0RF-z9hvuxawDXePLjPHmsv8cF4pWDU',
    appId: '1:267525384609:ios:4b0b549091e3c5664d83e0',
    messagingSenderId: '267525384609',
    projectId: 'movie-app-91685',
    storageBucket: 'movie-app-91685.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0RF-z9hvuxawDXePLjPHmsv8cF4pWDU',
    appId: '1:267525384609:ios:4b0b549091e3c5664d83e0',
    messagingSenderId: '267525384609',
    projectId: 'movie-app-91685',
    storageBucket: 'movie-app-91685.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBalbxWdFzgMFRW2SZu-5edtT1YWQi71Ng',
    appId: '1:267525384609:web:4dfcb4c5b220bb104d83e0',
    messagingSenderId: '267525384609',
    projectId: 'movie-app-91685',
    authDomain: 'movie-app-91685.firebaseapp.com',
    storageBucket: 'movie-app-91685.firebasestorage.app',
    measurementId: 'G-7918702FG9',
  );
}
